#!/usr/bin/env python3
# Copyright (c) 2020 Antmicro <https://www.antmicro.com>

import sys
import yaml
import shlex
import argparse
import tempfile

parser = argparse.ArgumentParser()
parser.add_argument("target", type=str)
parser.add_argument("file", type=argparse.FileType("r"), default=sys.stdin)

args = parser.parse_args()

try:
    data = yaml.safe_load(args.file)
except:
    print("Failed to parse YAML file.", file=sys.stderr)
    sys.exit(1)

try:
    data = data[args.target]
except:
    print("Invalid target.", file=sys.stderr)
    sys.exit(2)

incdirs=",".join(data.get("incdirs", []))
filelist = tempfile.NamedTemporaryFile(mode="w", delete=False)
print("\n".join(data.get("files", [])), file=filelist)

print(f"--include_dir_paths {shlex.quote(incdirs)} --file_list_path {shlex.quote(filelist.name)}")

