#!/usr/bin/env python3
# Copyright (c) 2020 Antmicro <https://www.antmicro.com>

import argparse
import os
import shlex
import tempfile
from pathlib import Path

from fusesoc.coremanager import CoreManager, DependencyError
from fusesoc.config import Config
from fusesoc.librarymanager import Library
from fusesoc.vlnv import Vlnv

parser = argparse.ArgumentParser()
parser.add_argument("core", type=str)
args = parser.parse_args()

cm = CoreManager(Config())
cm.add_library(Library(".", "."))

incdirs = []
filelist = tempfile.NamedTemporaryFile(mode="w", delete=False, dir=os.getcwd(), prefix="file_list.", suffix=".txt")

cores = cm.get_depends(Vlnv(args.core), flags={})
for core in cores:
    core.setup()
    root = core.files_root
    for fs in core.filesets.values():
        for f in fs.files:
            if f.is_include_file:
                dirname = str(Path(root, f.name).parent)
                if dirname not in incdirs:
                    incdirs.append(str(dirname))
            elif f.file_type == "systemVerilogSource":
                print(str(Path(root, f.name)), file=filelist)

incdirs = ",".join(incdirs)

print(f"--include_dir_paths {shlex.quote(incdirs)} --file_list_path {shlex.quote(filelist.name)}")
